# Generated by Django 5.2.6 on 2026-06-23 13:32

import django.db.models.deletion
import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('in_reply_to', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('references', models.TextField(blank=True, null=True)),
                ('from_addr', models.EmailField(max_length=320)),
                ('subject', models.CharField(blank=True, default='', max_length=1024)),
                ('body_text', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(default=dict)),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('received_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'raw_emails',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_ref', models.CharField(default=onboarding.models.make_ticket_ref, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('awaiting_validation', 'Awaiting validation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('requires_manual_review', 'Requires manual review')], db_index=True, default='received', max_length=32)),
                ('applicant_name', models.CharField(blank=True, default='', max_length=255)),
                ('applicant_email', models.EmailField(blank=True, db_index=True, default='', max_length=320)),
                ('applicant_phone', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('applicant_address', models.TextField(blank=True, default='')),
                ('applicant_dob', models.DateField(blank=True, null=True)),
                ('applicant_age', models.PositiveIntegerField(blank=True, null=True)),
                ('parsed_source', models.JSONField(blank=True, default=dict)),
                ('sla_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sla_breached', models.BooleanField(default=False)),
                ('raw_email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='onboarding.rawemail')),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(default='email', max_length=32)),
                ('template', models.CharField(max_length=64)),
                ('to_addr', models.CharField(max_length=320)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='onboarding.ticket')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='onboarding.ticket')),
            ],
            options={
                'db_table': 'idempotency_keys',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=512)),
                ('content_type', models.CharField(choices=[('pdf', 'PDF'), ('jpg', 'JPG'), ('png', 'PNG')], max_length=8)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('storage_path', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsed', 'Parsed'), ('invalid', 'Invalid')], default='uploaded', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('extracted_fields', models.JSONField(blank=True, default=dict)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='onboarding.ticket')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('email_received', 'Email received'), ('ticket_created', 'Ticket created'), ('documents_uploaded', 'Documents uploaded'), ('document_parsed', 'Document parsed'), ('validation_passed', 'Validation passed'), ('validation_failed', 'Validation failed'), ('notification_sent', 'Notification sent'), ('status_updated', 'Status updated'), ('duplicate_merged', 'Duplicate merged'), ('sla_breached', 'SLA breached'), ('processing_failed', 'Processing failed'), ('reprocess_requested', 'Reprocess requested')], db_index=True, max_length=32)),
                ('message', models.CharField(blank=True, default='', max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='onboarding.ticket')),
            ],
            options={
                'db_table': 'ticket_events',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(db_index=True, max_length=64)),
                ('passed', models.BooleanField()),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='onboarding.ticket')),
            ],
            options={
                'db_table': 'validation_results',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
