# Generated by Django 5.2.6 on 2026-06-24 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_document_sha256_document_uniq_ticket_sha256'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=128)),
                ('error', models.TextField()),
                ('reprocessed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dead_letters', to='onboarding.ticket')),
            ],
            options={
                'db_table': 'dead_letters',
                'ordering': ['-created_at'],
            },
        ),
    ]
