# Generated by Django 5.2.6 on 2026-06-24 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_deadletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawemail',
            name='thread_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_emails', to='onboarding.ticket'),
        ),
    ]
