# Generated by Django 5.2.6 on 2026-06-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_rawemail_thread_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdempotencyKey',
        ),
    ]
